# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agaDnIepT8vXnjgdxDvIErtqbOAex-7m
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer , util
#Load the model
model=SentenceTransformer('all-miniLM-L6-V2')
#Take input from user
text1=input("enter text1: ")
text2=input("enter text2: ")
#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculating similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n Similarity Score:",round(float(similarity),2))
if similartity>0.75:
  print("similarity level:High")
elif similarity>0.4:
    print("similarity level:medium")
else:
      print("similarity level:low")

from google.colab import drive
drive.mount('/content/drive')